---

- block:
    - name: create file by template file
      template:
        src: "{{ template_src }}"
        dest: "{{ template_dest }}"
      register: template_result
  when: template_src is defined

- block:
    - name: create file by inline template
      copy:
        content: "{{ template_content }}"
        dest: "{{ template_dest }}"
      register: template_result
  when: template_content is defined

...
